import{a as v,S as b,i as n}from"./assets/vendor-DFCQGEf1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();async function u(s,t){const r="https://pixabay.com/api/",i="50647927-495c70707602983112414a885",e=new URLSearchParams({key:i,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:t}),o=`${r}?${e}`;return(await v.get(o)).data}const f=document.querySelector(".gallery"),m=document.querySelector(".load-more"),p=document.querySelector(".loader"),S=new b(".gallery a");function h(s){const t=s.map(r=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${r.likes}</p>
          <p>Views: ${r.views}</p>
          <p>Comments: ${r.comments}</p>
          <p>Downloads: ${r.downloads}</p>
        </div>
      </li>
      `).join("");f.insertAdjacentHTML("beforeend",t),S.refresh()}function P(){f.innerHTML=""}function g(){p.classList.add("visible")}function y(){p.classList.remove("visible")}function L(){m.classList.remove("hidden")}function d(){m.classList.add("hidden")}const R=document.querySelector(".form"),$=document.querySelector(".load-more");let a=1,l="";const w=15;R.addEventListener("submit",async s=>{if(s.preventDefault(),l=s.target.elements["search-text"].value.trim(),a=1,l===""){n.warning({message:"Please enter a search query!",position:"topRight"});return}P(),d(),g();try{const t=await u(l,a);if(t.hits.length===0){n.error({message:"Sorry, no images found!",position:"topRight"});return}h(t.hits),t.totalHits>w?L():d()}catch(t){n.error({message:"An error occurred while fetching images!",position:"topRight"}),console.error(t)}finally{y()}});$.addEventListener("click",async()=>{a+=1,g(),d();try{const s=await u(l,a);h(s.hits);const t=Math.ceil(s.totalHits/w);a>=t?(d(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L();const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch(s){n.error({message:"An error occurred while fetching more images!",position:"topRight"}),console.error(s)}finally{y()}});
//# sourceMappingURL=index.js.map
